// ─── COMPONENT PROP TYPES ────────────────────────────────────────────────────
// Props for the main DataTable component and its render prop callbacks.

import type { ReactNode, MouseEvent, KeyboardEvent } from 'react';
import type { MultiSortState, FilterState, FilterValue, CursorPagination } from '@/components/ui/data-table/types/core';
import type { Column } from '@/components/ui/data-table/types/column';
import type { DataTableError } from '@/components/ui/data-table/errors/base';
import type { ErrorSeverity } from '@/components/ui/data-table/errors/severity';
import type { ErrorHub, ErrorHubOptions } from '@/components/ui/data-table/errors/error-hub';
import type { RecoveryStrategyConfig } from '@/components/ui/data-table/errors/recovery';

// ─── ERROR CONFIGURATION ──────────────────────────────────────────────────────

/**
 * Configuration for error handling in DataTable.
 *
 * @example
 * ```tsx
 * <DataTable
 *   errorConfig={{
 *     onError: (error) => {
 *       // Send to telemetry
 *       analytics.track("datatable_error", error.toJSON());
 *     },
 *     minReportSeverity: ErrorSeverity.ERROR,
 *     showInlineErrors: true,
 *   }}
 * />
 * ```
 */
export interface DataTableErrorConfig {
  /**
   * Callback fired when any error occurs.
   * Use for logging, telemetry, or custom error handling.
   *
   * @example
   * ```ts
   * onError: (error) => {
   *   Sentry.captureException(error);
   * }
   * ```
   */
  onError?: (error: DataTableError) => void;

  /**
   * Custom ErrorHub instance.
   * If not provided, a new hub is created for this table instance.
   *
   * Use this to share error state across multiple tables or
   * to integrate with a global error management system.
   */
  errorHub?: ErrorHub;

  /**
   * Options for the ErrorHub (ignored if `errorHub` is provided).
   * Use this for simple configuration without creating a hub manually.
   */
  errorHubOptions?: ErrorHubOptions;

  /**
   * Custom recovery strategies to add or override defaults.
   * Strategies are matched by error code.
   *
   * @example
   * ```ts
   * recoveryStrategies: [
   *   {
   *     id: "custom-filter-recovery",
   *     codes: ["DT_506"],
   *     recover: () => false,
   *     getFallback: () => true, // Include all rows
   *   }
   * ]
   * ```
   */
  recoveryStrategies?: RecoveryStrategyConfig[];

  /**
   * Minimum severity level to report to `onError`.
   * Errors below this level are still logged but not reported.
   * @default ErrorSeverity.WARNING
   */
  minReportSeverity?: ErrorSeverity;

  /**
   * Whether to show inline error indicators in cells when render fails.
   * @default true
   */
  showInlineErrors?: boolean;

  /**
   * Custom renderer for cell-level errors.
   * Called when a cell's render function throws.
   */
  errorCellRenderer?: (error: DataTableError) => ReactNode;

  /**
   * Whether to enable automatic error recovery attempts.
   * When enabled, the table will try to recover from errors
   * using registered recovery strategies.
   * @default true
   */
  enableRecovery?: boolean;

  /**
   * Whether to validate columns on every render (not just development).
   * Enable for strict mode that catches configuration errors in production.
   * @default false (only validates in development)
   */
  strictValidation?: boolean;
}

// ─── ROW ACTIVATION EVENT ────────────────────────────────────────────────────

/**
 * Event passed to onRowClick callback.
 * Can be either a mouse click or keyboard activation (Enter/Space).
 * Use `source` to distinguish between the two.
 */
export type RowActivationEvent =
  | { source: 'mouse'; event: MouseEvent }
  | { source: 'keyboard'; event: KeyboardEvent };

// ─── RENDER PROP TYPES ───────────────────────────────────────────────────────

/**
 * Props passed to custom header render function
 */
export interface DataTableHeaderRenderProps<T> {
  columns: Column<T>[];
  /** Multi-sort state - array of sort items in priority order */
  sortState: MultiSortState;
  onSort: (key: string, addToMultiSort?: boolean) => void;
  selectable: boolean;
  allSelected: boolean;
  indeterminate: boolean;
  onSelectAll: (checked: boolean) => void;
  enableExpansion: boolean;
}

/**
 * Props passed to custom toolbar render function
 */
export interface DataTableToolbarRenderProps<T> {
  columns: Column<T>[];
  searchValue: string;
  onSearchChange: (value: string) => void;
  filters: FilterState;
  onFilterChange: (key: string, value: FilterValue) => void;
  onClearFilters: () => void;
  selectedCount: number;
  totalCount: number;
  visibleColumns: Column<T>[];
  onColumnVisibilityChange: (key: string) => void;
  onShowAllColumns: () => void;
}

// ─── REMOTE DATA PROPS ───────────────────────────────────────────────────────

/**
 * Props generated by useRemoteDataTable hook for DataTable
 */
export interface RemoteDataTableProps<T> {
  data: T[];
  loading: boolean;
  refreshing: boolean;
  onRefresh: () => Promise<void>;
  pagination: {
    mode: 'cursor';
    cursor: CursorPagination;
  };
  controlled: {
    searchValue: string;
    filters: FilterState;
    sortState: MultiSortState;
  };
  callbacks: {
    onSearchChange: (value: string) => void;
    onFilterChange: (filters: FilterState) => void;
    onSortChange: (sortState: MultiSortState) => void;
  };
  totalCount?: number;
}
